create extension if not exists pgcrypto;

create table public.funnel_events (
  id bigint generated by default as identity primary key,
  session_id uuid not null,
  event_name text not null check (event_name in ('started','answered','step_viewed','completed')),
  step_key text not null,
  step_index integer not null check (step_index between 0 and 20),
  answer jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index funnel_events_session_created_idx on public.funnel_events (session_id, created_at);
create index funnel_events_step_created_idx on public.funnel_events (step_index, created_at);
create index funnel_events_event_created_idx on public.funnel_events (event_name, created_at);

create table public.leads_nutricionista (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null unique,
  nome text not null,
  whatsapp text not null,
  cidade text not null,
  instagram text,
  objetivo text not null,
  nivel_interesse text not null,
  respostas jsonb not null default '{}'::jsonb,
  consentimento boolean not null default false,
  origem text not null default 'bio_instagram',
  status text not null default 'novo',
  criado_em timestamptz not null default now()
);

create index leads_nutricionista_criado_em_idx on public.leads_nutricionista (criado_em desc);
create index leads_nutricionista_interesse_idx on public.leads_nutricionista (nivel_interesse);

alter table public.funnel_events enable row level security;
alter table public.leads_nutricionista enable row level security;

revoke all on public.funnel_events from anon, authenticated;
revoke all on public.leads_nutricionista from anon, authenticated;
grant insert on public.funnel_events to anon, authenticated;
grant usage, select on sequence public.funnel_events_id_seq to anon, authenticated;
grant insert on public.leads_nutricionista to anon, authenticated;
grant select on public.funnel_events to authenticated;
grant select on public.leads_nutricionista to authenticated;

create policy funnel_events_public_insert on public.funnel_events
for insert to anon, authenticated
with check (event_name in ('started','answered','step_viewed','completed') and step_index between 0 and 20);

create policy funnel_events_admin_read on public.funnel_events
for select to authenticated
using (((select auth.jwt()) ->> 'email') = 'matheusgaleno11@gmail.com');

create policy leads_public_insert on public.leads_nutricionista
for insert to anon, authenticated
with check (consentimento = true and length(nome) between 2 and 160 and length(whatsapp) between 10 and 40);

create policy leads_admin_read on public.leads_nutricionista
for select to authenticated
using (((select auth.jwt()) ->> 'email') = 'matheusgaleno11@gmail.com');
